SAFE/Controllers/EmpresaController.cs
using SAFE.Domain.Forms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAFE.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        [Authorize]
        public ActionResult Index()
        {
            FormEmpresa _form = new FormEmpresa();

            _form.listaEmpresas = FormServiciosGeneralesFactory.obtenerEmpresas();

            return View(_form);
        }
    }
}

SAFE/Views/Shared/_Layout.cshtml
@using System.Text
@using System.Web
@using System.Web.Helpers
@using System.Web.Mvc.Html
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title SAFE</title>
    @Styles.Render("~/bundles/fonts")
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrapminjs")
    @Scripts.Render("~/bundles/customjs")    
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">
    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
            var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;)r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: 'dbdd3e59-f502-488e-b84d-4dd2cce0e659'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body class="body">
    <script>
        $(document).ready(function () {

            $('#toggleUsuarioEmpresa').bootstrapToggle('on');

            var isValid = '@Html.Raw(Json.Encode(ViewData.ModelState.IsValid))';

            if (isValid != 'true') {
                $('#ValidationModal').modal('show');
                $('#btnObservaciones').prop('disabled', false);


                //$('#toggleUsuarioEmpresa').on('click', function () {
                //    alert(123);
                //});

                //$('#login-dp').on('click', function (e) {
                //    //$(this).next('ul').toggle();
                //    console.log(e);
                //    console.log(e.target);
                //    var target = $(e.target);

                //    if ((target.is('input') || target.is('label')))
                //        e.stopPropagation();
                //});
            }

            @if (Session.Count > 0)
            {
                if (Session["msjForm"] != null && !string.IsNullOrEmpty(Session["msjForm"].ToString())) {
                    @:mdlMensaje('Información', '@Encoding.UTF8.GetString(Encoding.Default.GetBytes(Session["msjForm"].ToString()))');
                    Session["msjForm"] = string.Empty;
                }
            }
        });
    </script>
    <header class="header">
        <div class="container">
            <div class="site-header clearfix col-md-12">
                <div class="col-lg-3 col-md-3 col-sm-3 title-area">
                    
                </div>
                <div class="col-lg-9 col-md-9 col-sm-9">
                    <div id="nav">
                        <div class="container clearfix">
                            <ul id="jetmenu" class="jetmenu blue">
                                @if (Request.IsAuthenticated)
                                {
                                    <li class="pull-right">
                                        <a href="#">@($"Hola, {User.Identity.Name}")</a>
                                        <ul class="dropdown">
                                            <li>@Html.ActionLink("Cerrar sesión", "LogOff", "Account")</li>
                                        </ul>
                                    </li>
                                    <li class="pull-right"> @Html.ActionLink("Empresas", "Index", "Empresa")</li>

                                }
                                else
                                {
                                    <li class="pull-right">@Html.ActionLink("Acceder", "Login", "Account")</li>
                                    <li class="pull-right">@Html.ActionLink("BYPASS LOGIN", "LoginFalso", "Account")</li>
                                }

                                @*<li>
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Evaluaciones en terreno</a>
                                        <ul class="dropdown">
                                            <li>
                                                <ul>
                                                    <li>@Html.ActionLink("Em", "Index", "Empresa")</li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>*@
                                @*<li>
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Capacitaciones</a>
                                        <ul class="dropdown">
                                            <li>
                                                <a href="#">Cliente</a>
                                                <ul>

                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">Técnico/Ingeniero/Supervisor</a>
                                                <ul>

                                                    <li></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>*@
                                @*<li>
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Visitas médicas</a>
                                        <ul class="dropdown">
                                            <li>
                                                <a href="#">Cliente</a>
                                                <ul>

                                                </ul>
                                            </li>


                                            <li>
                                                <a href="#">Técnico/Ingeniero/Supervisor</a>
                                                <ul>

                                                    <li></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>*@
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- end header -->
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@
    <div class="body-content">
        @*<section class="post-wrapper-top">
                <div class="container">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <ul class="breadcrumb">
                            <li><a href="/">Inicio</a></li>
                            <li>@ViewBag.Title</li>
                        </ul>
                        <h2>@ViewBag.Title</h2>
                    </div>
                </div>
            </section>*@
        <!-- end post-wrapper-top -->
        @RenderBody()
        <hr />
        <div class="dmtop">Scroll to Top</div>
        <div id="logoCarga" class="loader loader-default"></div>
        <!-- Modal -->
        <div id="mdlMensaje" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 id="mdlTitulo" class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                        @Html.Raw("<p id='mdlContenido'></p>")
                        @*<p id="mdlContenido"></p>*@
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="ValidationModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                        <h4 class="modal-title" id="ModalLabel">Observaciones</h4>
                    </div>
                    <div class="modal-body">
                        @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationSummary("", new { id = "validationSummary" }).ToHtmlString()))
                        @*@Html.ValidationSummary("", new { id = "validationSummary" })*@
                        <span id="mensajeValidacionAux" class="validation-summary-errors"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" id="btnObservaciones" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer COL-md-12">
        <div class="container">
            <div class="widget col-lg-6 col-md-6 col-sm-12">
                <h4 class="title">Sobre nosotros</h4>
                <p>
                    Proyecto portafolio Duoc 2018
                    <ul>
                        <li>
                            Integrantes
                            <ol>
                                <li>@*<i class="fa fa-money"></i>*@ Adolfo Cid</li>
                                <li>@*<i class="fa fa-mobile-phone"></i>*@ Gerardo Garrido</li>
                                <li> @*<i class="fa fa-gears"></i>*@ Gonzalo Galdames</li>
                                <li> <i class="glyphicon glyphicon-shopping-cart"></i> Claudio Vergara</li>
                                <li> @*<i class="glyphicon glyphicon-headphones"></i>*@ Enrique Venegas</li>
                            </ol>
                        </li>
                        <li>
                            Profesor
                            <ol>
                                <li>
                                    César Burgos
                                </li>
                            </ol>
                        </li>
                    </ul>
                </p>
            </div>
            <div class="widget col-lg-6 col-md-6 col-sm-12">
                <h4 class="title">Ponte en contacto</h4>
                <ul class="contact_details">
                    <li><i class="fa fa-envelope-o"></i> contacto@safe.com</li>
                    <li><i class="fa fa-phone-square"></i> +56 2 1111 1111</li>
                    <li><i class="fa fa-home"></i> Antonio Varas 666, Providencia, Región Metropolitana</li>
                </ul>
            </div>
        </div>

    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>

SAFE/Views/Shared/_ValidationPartial.cshtml
@using System.Web


<div class="modal fade" id="ValidationModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <h4 class="modal-title" id="ModalLabel">Observaciones</h4>
            </div>
            <div class="modal-body">
                @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationSummary("", new { id = "validationSummary"}).ToHtmlString()))
                @*@Html.ValidationSummary("", new { id = "validationSummary" })*@
                <span id="mensajeValidacionAux" class="text-danger"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnObservaciones" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

SAFE/Views/Shared/lostpage.cshtml
@{
    ViewBag.Title = "Página no encontrada";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="section1">
    <div class="container clearfix">
        <div class="content col-lg-12 col-md-12 col-sm-12 clearfix">
            <div class="notfound">
                <h1 class="big-title">Página no encontrada!</h1>
                <h4 class="small-title">
                    La página que estás buscando no existe<br>

                </h4>
                <a class="" href="@Url.Action("Index", "Home")">Volver a página de inicio</a>
            </div>
        </div>
    </div>
</section>